server:
  port: 9000
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful
spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic # Type of connection pool (elastic, fixed, or disabled)
          max-idle-time: 15s # Idle time after which the communication channel will be closed
          max-life-time: 60s # Time after which the communication channel will be closed
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
           - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
           - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
      default-filters:
        - SaveSession # Ensures the session data is saved before forwarding a request downstream
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10 # Number of tokens dripped in the bucket each second
              burstCapacity: 20 # Allows request bursts of up to 20 requests
              requestedTokens: 1 # How many tokens a request costs
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException
            backoff: # Retries with a delay computed as ?firstBackoff * (factor ^ n)?
              first-backoff: 50ms
              max-backoff: 500ms
              factor: 2
              basedOnPreviousValue: false
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
resilience4j:
  circuitbreaker:
    configs:
      default: # Default configuration bean for all circuit breakers
        slidingWindowSize: 20 # The size of the sliding window used to record the outcome of calls when the circuit is closed
        permittedNumberOfCallsInHalfOpenState: 5 # Number of permitted calls when the circuit is half-open
        failureRateThreshold: 50 # When the failure rate is above the threshold, the circuit becomes open.
        waitDurationInOpenState: 15000 # Waiting time before moving from open to half-open (ms)
  timelimiter:
    configs:
      default: # Default configuration bean for all time limiters
        timeoutDuration: 5s #Configures a timeout (seconds)
logging:
  level:
    io.github.resilience4j: DEBUG